<a href="https://colab.research.google.com/github/soichiroiwashita-create/looker_trainee_iwashi/blob/master/preprocess_knock_SQL_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# データサイエンス100本ノック（構造化データ加工編） - SQL (Google Colab環境)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](http://colab.research.google.com/github/rootassist/100knocks-preprocess-inSQLandPython-withColab/blob/master/preprocess_knock_SQL_Colab.ipynb)

## はじめに
- 初めに以下の「環境構築用のセル」を実行してください（再開時にも実行する必要があります）
- データベースはPostgreSQL13です
- セルに %%sql と記載することでSQLを発行することができます
- jupyterからはdescribeコマンドによるテーブル構造の確認ができないため、テーブル構造を確認する場合はlimitを指定したSELECTなどで代用してください
- サーバーは以下のように設定して起動しています
  - Port: 5432
  - database名: dsdojo_db
  - ユーザ名: padwan
  - パスワード: padwan12345
- データ（CSVファイル）はこのリポジトリからcurlコマンドで/tmp/data/100knock-preprocess/ディレクトリの下へ取得した上で読み込んでいます
- CSVファイルの出力などは/tmp/dataに対して行います
- 大量出力を行うとJupyterが固まることがあるため、出力件数は制限することを推奨します（設問にも出力件数を記載）
    - 結果確認のために表示させる量を適切にコントロールし、作業を軽快にすすめる技術もデータ加工には求められます
- 解答にあたって、処理は複数回に分けても構いません
- 名前、住所等はダミーデータであり、実在するものではありません
- ノートは、Googleドライブの下のColab Notebooksフォルダの下に保存されます

In [46]:
#環境構築用のセル
# Import the repository signing key:
!sudo apt install curl ca-certificates
!sudo install -d /usr/share/postgresql-common/pgdg
!sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc

# Create the repository configuration file:
!sudo sh -c "echo 'deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt '$(grep -oP 'VERSION_CODENAME=\K\w+' /etc/os-release)'-pgdg main' > /etc/apt/sources.list.d/pgdg.list"

# Update the package lists:
!sudo apt update

# Install the 13th version of PostgreSQL:
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql-13
!sudo pg_ctlcluster 13 main start

!sudo -u postgres psql -U postgres -c "create database dsdojo_db;"
!sudo -u postgres psql -U postgres -c "create user padwan with superuser;"
!sudo -u postgres psql -U postgres -c "alter user padwan password 'padwan12345';"
!sudo -u postgres psql -U postgres -c "grant all privileges on database dsdojo_db to padwan;"
!sudo -u postgres psql -U postgres -c "grant pg_read_server_files to padwan;"
!sudo -u postgres psql -U postgres -c "grant pg_write_server_files to padwan;"

!sudo -u postgres psql -U postgres -d dsdojo_db -c "create table customer(customer_id VARCHAR(14), customer_name VARCHAR(20), gender_cd VARCHAR(1), gender VARCHAR(2), birth_day DATE, age INTEGER, postal_cd VARCHAR(8), address VARCHAR(128), application_store_cd VARCHAR(6), application_date VARCHAR(8), status_cd VARCHAR(12), primary key (customer_id));create table category( category_major_cd VARCHAR(2), category_major_name VARCHAR(32), category_medium_cd VARCHAR(4), category_medium_name VARCHAR(32), category_small_cd VARCHAR(6), category_small_name VARCHAR(32), primary key (category_small_cd));create table product( product_cd VARCHAR(10), category_major_cd VARCHAR(2), category_medium_cd VARCHAR(4), category_small_cd VARCHAR(6), unit_price INTEGER, unit_cost INTEGER, primary key (product_cd));create table store( store_cd VARCHAR(6), store_name VARCHAR(128), prefecture_cd VARCHAR(2), prefecture VARCHAR(5), address VARCHAR(128), address_kana VARCHAR(128), tel_no VARCHAR(20), longitude NUMERIC, latitude NUMERIC, floor_area NUMERIC, primary key (store_cd));create table receipt( sales_ymd INTEGER, sales_epoch INTEGER, store_cd VARCHAR(6), receipt_no SMALLINT, receipt_sub_no SMALLINT, customer_id VARCHAR(14), product_cd VARCHAR(10), quantity INTEGER, amount INTEGER, primary key (sales_ymd, store_cd, receipt_no, receipt_sub_no));create table geocode( postal_cd VARCHAR(8), prefecture VARCHAR(4), city VARCHAR(30), town VARCHAR(30), street VARCHAR(30), address VARCHAR(30), full_address VARCHAR(80), longitude NUMERIC, latitude NUMERIC);"

!sudo mkdir -p /tmp/data/100knock-preprocess
!sudo chmod -R 777 /tmp/data

table_names = ('customer', 'category', 'product', 'receipt', 'store', 'geocode')
base = "/tmp/data/100knock-preprocess/"
baseurl = "https://raw.githubusercontent.com/The-Japan-DataScientist-Society/100knocks-preprocess/master/docker/work/data/"
for table_name in table_names:
   CURLCMD="curl -o "+base+table_name+".csv "+baseurl+table_name+".csv"
   !sudo -u postgres $CURLCMD
   COPYCMD="\copy "+table_name+" from '"+base+table_name+".csv' encoding 'utf8' csv header;"
   !sudo -u postgres psql -U postgres -d dsdojo_db -c "$COPYCMD"

!pip install prettytable==3.6.0

%load_ext sql
%config SqlMagic.autopandas = True
%sql postgresql://padwan:padwan12345@localhost:5432/dsdojo_db

<>:36: SyntaxWarning: invalid escape sequence '\c'
<>:36: SyntaxWarning: invalid escape sequence '\c'
/tmp/ipykernel_7479/793371259.py:36: SyntaxWarning: invalid escape sequence '\c'
  COPYCMD="\copy "+table_name+" from '"+base+table_name+".csv' encoding 'utf8' csv header;"

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.24).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4812  100  4812    0     0  12783      0 --:--:-- --:--:-- --:--:-- 12763
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,632 B in 1s (5,245 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
15 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Cluster is already running.
ERROR:  database "dsdojo_db" already exists
ERROR:  role "padwan" already exists
ALTER ROLE
GRANT
NOTICE:  role "padwan" is already a member of role "pg_read_server_files"
GRANT ROLE
NOTICE:  role "padwan" is already a member of role "pg_write_server_files"
GRANT ROLE
ERROR:  relation "customer" already exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2825k  100 2825k    0     0  13.6M      0 --:--:-- --:--:-- --:--:-- 13.6M
ERROR:  duplicate key value violates unique constraint "customer_pkey"
DETAIL:  Key (customer_id)=(CS021313000114) already exists.
CONTEXT:  COPY customer, line 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12885  100 12885    0     0   153k      0 --:--:-- --:--:-- --:--:--  155k
ERROR:  duplicate key value violates unique constraint "category_pkey"
DETAIL:  Key (category_small_cd)=(040101) already exists.
CONTEXT:  COPY category, line 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  341k  100  341k    0     0  3423k      0 --:--:-- --:--:-- --:--:-- 3447k
ERROR:  duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (product_cd)=(P040101001) already exists.
CONTEXT:  COPY product, line 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6726k  100 6726k    0     0  26.0M      0 --:--:-- --:--:-- --:--:-- 25.9M
ERROR:  duplicate key value violates unique constraint "receipt_pkey"
DETAIL:  Key (sales_ymd, store_cd, receipt_no, receipt_sub_no)=(20181103, S14006, 112, 1) already exists.
CONTEXT:  COPY receipt, line 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9475  100  9475    0     0   125k      0 --:--:-- --:--:-- --:--:--  126k
ERROR:  duplicate key value violates unique constraint "store_pkey"
DETAIL:  Key (store_cd)=(S12014) already exists.
CONTEXT:  COPY store, line 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.2M  100 12.2M    0     0  39.6M      0 --:--:-- --:--:-- --:--:-- 39.6M
COPY 127252
Requirement already satisfied: prettytable==3.6.0 in /usr/local/lib/python3.12/dist-packages (3.6.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable==3.6.0) (0.6.0)
The sql extension is already loaded. To reload it, use:
  %reload_ext sql

# 使い方
- セルの先頭に%%sqlと記載し、２行目以降にSQLを記述することでJupyterからPostgreSQLに対しSQLを実行できます。

In [ ]:
%%sql
SELECT 'このように実行できます' AS sample;

# データ加工100本ノック

---
> S-001: レシート明細データ（receipt）から全項目の先頭10件を表示し、どのようなデータを保有しているか目視で確認せよ。

In [47]:
%%sql
select *
from receipt
limit 10 ;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,sales_ymd,sales_epoch,store_cd,receipt_no,receipt_sub_no,customer_id,product_cd,quantity,amount
0,20181103,1541203200,S14006,112,1,CS006214000001,P070305012,1,158
1,20181118,1542499200,S13008,1132,2,CS008415000097,P070701017,1,81
2,20170712,1499817600,S14028,1102,1,CS028414000014,P060101005,1,170
3,20190205,1549324800,S14042,1132,1,ZZ000000000000,P050301001,1,25
4,20180821,1534809600,S14025,1102,2,CS025415000050,P060102007,1,90
5,20190605,1559692800,S13003,1112,1,CS003515000195,P050102002,1,138
6,20181205,1543968000,S14024,1102,2,CS024514000042,P080101005,1,30
7,20190922,1569110400,S14040,1102,1,CS040415000178,P070501004,1,128
8,20170504,1493856000,S13020,1112,2,ZZ000000000000,P071302010,1,770
9,20191010,1570665600,S14027,1102,1,CS027514000015,P071101003,1,680

---
> S-002: レシート明細データ（receipt）から売上年月日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、10件表示せよ。

In [48]:
%%sql
select sales_ymd,customer_id,product_cd,amount
from receipt
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

   sales_ymd     customer_id  product_cd  amount
0   20181103  CS006214000001  P070305012     158
1   20181118  CS008415000097  P070701017      81
2   20170712  CS028414000014  P060101005     170
3   20190205  ZZ000000000000  P050301001      25
4   20180821  CS025415000050  P060102007      90
5   20190605  CS003515000195  P050102002     138
6   20181205  CS024514000042  P080101005      30
7   20190922  CS040415000178  P070501004     128
8   20170504  ZZ000000000000  P071302010     770
9   20191010  CS027514000015  P071101003     680

---
> S-003: レシート明細データ（receipt）から売上年月日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、10件表示せよ。ただし、sales_ymdをsales_dateに項目名を変更しながら抽出すること。

In [49]:
%%sql
select sales_ymd as sales_date,customer_id,product_cd,amount
from receipt
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

   sales_date     customer_id  product_cd  amount
0    20181103  CS006214000001  P070305012     158
1    20181118  CS008415000097  P070701017      81
2    20170712  CS028414000014  P060101005     170
3    20190205  ZZ000000000000  P050301001      25
4    20180821  CS025415000050  P060102007      90
5    20190605  CS003515000195  P050102002     138
6    20181205  CS024514000042  P080101005      30
7    20190922  CS040415000178  P070501004     128
8    20170504  ZZ000000000000  P071302010     770
9    20191010  CS027514000015  P071101003     680

---
> S-004: レシート明細データ（receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、以下の条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"

In [50]:
%%sql
select sales_ymd,customer_id,product_cd,amount
from receipt
where customer_id = 'CS018205000001';

 * postgresql://padwan:***@localhost:5432/dsdojo_db
12 rows affected.

    sales_ymd     customer_id  product_cd  amount
0    20180911  CS018205000001  P071401012    2200
1    20180414  CS018205000001  P060104007     600
2    20170614  CS018205000001  P050206001     990
3    20170614  CS018205000001  P060702015     108
4    20190216  CS018205000001  P071005024     102
5    20180414  CS018205000001  P071101002     278
6    20190226  CS018205000001  P070902035     168
7    20190924  CS018205000001  P060805001     495
8    20190226  CS018205000001  P071401020    2200
9    20180911  CS018205000001  P071401005    1100
10   20190216  CS018205000001  P040101002     218
11   20190924  CS018205000001  P091503001     280

---
> S-005: レシート明細データ（receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、以下の全ての条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"
> - 売上金額（amount）が1,000以上

In [51]:
%%sql
select sales_ymd,customer_id,product_cd,amount
from receipt
where customer_id = 'CS018205000001' and amount >=1000;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
3 rows affected.

   sales_ymd     customer_id  product_cd  amount
0   20180911  CS018205000001  P071401012    2200
1   20190226  CS018205000001  P071401020    2200
2   20180911  CS018205000001  P071401005    1100

---
> S-006: レシート明細データ（receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上数量（quantity）、売上金額（amount）の順に列を指定し、以下の全ての条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"
> - 売上金額（amount）が1,000以上または売上数量（quantity）が5以上

In [52]:
%%sql
select sales_ymd,customer_id,product_cd,quantity,amount
from receipt
where customer_id = 'CS018205000001' and (amount >=1000 or quantity >=5);

 * postgresql://padwan:***@localhost:5432/dsdojo_db
5 rows affected.

   sales_ymd     customer_id  product_cd  quantity  amount
0   20180911  CS018205000001  P071401012         1    2200
1   20180414  CS018205000001  P060104007         6     600
2   20170614  CS018205000001  P050206001         5     990
3   20190226  CS018205000001  P071401020         1    2200
4   20180911  CS018205000001  P071401005         1    1100

---
> S-007: レシート明細データ（receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、以下の全ての条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"
> - 売上金額（amount）が1,000以上2,000以下

In [53]:
%%sql
select sales_ymd,customer_id,product_cd,amount
from receipt
where customer_id = 'CS018205000001' and amount between 1000 and 2000;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
1 rows affected.

   sales_ymd     customer_id  product_cd  amount
0   20180911  CS018205000001  P071401005    1100

---
> S-008: レシート明細データ（receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、以下の全ての条件を満たすデータを抽出せよ。
> - 顧客ID（customer_id）が"CS018205000001"
> - 商品コード（product_cd）が"P071401019"以外

In [55]:
%%sql
select sales_ymd,customer_id,product_cd,amount
from receipt
where customer_id = 'CS018205000001' and product_cd != 'P071401019';

 * postgresql://padwan:***@localhost:5432/dsdojo_db
12 rows affected.

    sales_ymd     customer_id  product_cd  amount
0    20180911  CS018205000001  P071401012    2200
1    20180414  CS018205000001  P060104007     600
2    20170614  CS018205000001  P050206001     990
3    20170614  CS018205000001  P060702015     108
4    20190216  CS018205000001  P071005024     102
5    20180414  CS018205000001  P071101002     278
6    20190226  CS018205000001  P070902035     168
7    20190924  CS018205000001  P060805001     495
8    20190226  CS018205000001  P071401020    2200
9    20180911  CS018205000001  P071401005    1100
10   20190216  CS018205000001  P040101002     218
11   20190924  CS018205000001  P091503001     280

---
> S-009: 以下の処理において、出力結果を変えずにORをANDに書き換えよ。
>
> `SELECT * FROM store WHERE NOT (prefecture_cd = '13' OR floor_area > 900)`

In [56]:
%%sql
select *
from store
where prefecture_cd != '13' and floor_area <= 900 ;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
3 rows affected.

,store_cd,store_name,prefecture_cd,prefecture,address,address_kana,tel_no,longitude,latitude,floor_area
0,S14046,北山田店,14,神奈川県,神奈川県横浜市都筑区北山田一丁目,カナガワケンヨコハマシツヅキクキタヤマタイッチョウメ,045-123-4049,139.5916,35.56189,831.0
1,S14011,日吉本町店,14,神奈川県,神奈川県横浜市港北区日吉本町四丁目,カナガワケンヨコハマシコウホククヒヨシホンチョウヨンチョウメ,045-123-4033,139.6316,35.54655,890.0
2,S12013,習志野店,12,千葉県,千葉県習志野市芝園一丁目,チバケンナラシノシシバゾノイッチョウメ,047-123-4002,140.022,35.66122,808.0

---
> S-010: 店舗データ（store）から、店舗コード（store_cd）が"S14"で始まるものだけ全項目抽出し、10件表示せよ。

In [59]:
%%sql
select *
from store
where store_cd like 'S14%'
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,store_cd,store_name,prefecture_cd,prefecture,address,address_kana,tel_no,longitude,latitude,floor_area
0,S14010,菊名店,14,神奈川県,神奈川県横浜市港北区菊名一丁目,カナガワケンヨコハマシコウホククキクナイッチョウメ,045-123-4032,139.6326,35.50049,1732.0
1,S14033,阿久和店,14,神奈川県,神奈川県横浜市瀬谷区阿久和西一丁目,カナガワケンヨコハマシセヤクアクワニシイッチョウメ,045-123-4043,139.4961,35.45918,1495.0
2,S14036,相模原中央店,14,神奈川県,神奈川県相模原市中央二丁目,カナガワケンサガミハラシチュウオウニチョウメ,042-123-4045,139.3716,35.57327,1679.0
3,S14040,長津田店,14,神奈川県,神奈川県横浜市緑区長津田みなみ台五丁目,カナガワケンヨコハマシミドリクナガツタミナミダイゴチョウメ,045-123-4046,139.4994,35.52398,1548.0
4,S14050,阿久和西店,14,神奈川県,神奈川県横浜市瀬谷区阿久和西一丁目,カナガワケンヨコハマシセヤクアクワニシイッチョウメ,045-123-4053,139.4961,35.45918,1830.0
5,S14028,二ツ橋店,14,神奈川県,神奈川県横浜市瀬谷区二ツ橋町,カナガワケンヨコハマシセヤクフタツバシチョウ,045-123-4042,139.4963,35.46304,1574.0
6,S14012,本牧和田店,14,神奈川県,神奈川県横浜市中区本牧和田,カナガワケンヨコハマシナカクホンモクワダ,045-123-4034,139.6582,35.42156,1341.0
7,S14046,北山田店,14,神奈川県,神奈川県横浜市都筑区北山田一丁目,カナガワケンヨコハマシツヅキクキタヤマタイッチョウメ,045-123-4049,139.5916,35.56189,831.0
8,S14022,逗子店,14,神奈川県,神奈川県逗子市逗子一丁目,カナガワケンズシシズシイッチョウメ,046-123-4036,139.5789,35.29642,1838.0
9,S14011,日吉本町店,14,神奈川県,神奈川県横浜市港北区日吉本町四丁目,カナガワケンヨコハマシコウホククヒヨシホンチョウヨンチョウメ,045-123-4033,139.6316,35.54655,890.0

---
> S-011: 顧客データ（customer）から顧客ID（customer_id）の末尾が1のものだけ全項目抽出し、10件表示せよ。

In [60]:
%%sql
select *
from customer
where customer_id like '%1'
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,customer_id,customer_name,gender_cd,gender,birth_day,age,postal_cd,address,application_store_cd,application_date,status_cd
0,CS037613000071,六角 雅彦,9,不明,1952-04-01,66,136-0076,東京都江東区南砂**********,S13037,20150414,0-00000000-0
1,CS028811000001,堀井 かおり,1,女性,1933-03-27,86,245-0016,神奈川県横浜市泉区和泉町**********,S14028,20160115,0-00000000-0
2,CS040412000191,川井 郁恵,1,女性,1977-01-05,42,226-0021,神奈川県横浜市緑区北八朔町**********,S14040,20151101,1-20091025-4
3,CS028314000011,小菅 あおい,1,女性,1983-11-26,35,246-0038,神奈川県横浜市瀬谷区宮沢**********,S14028,20151123,1-20080426-5
4,CS039212000051,藤島 恵梨香,1,女性,1997-02-03,22,166-0001,東京都杉並区阿佐谷北**********,S13039,20171121,1-20100215-4
5,CS015412000111,松居 奈月,1,女性,1972-10-04,46,136-0071,東京都江東区亀戸**********,S13015,20150629,0-00000000-0
6,CS004702000041,野島 洋,0,男性,1943-08-24,75,176-0022,東京都練馬区向山**********,S13004,20170218,0-00000000-0
7,CS041515000001,栗田 千夏,1,女性,1967-01-02,52,206-0001,東京都多摩市和田**********,S13041,20160422,E-20100803-F
8,CS029313000221,北条 ひかり,1,女性,1987-06-19,31,279-0011,千葉県浦安市美浜**********,S12029,20180810,0-00000000-0
9,CS034312000071,望月 奈央,1,女性,1980-09-20,38,213-0026,神奈川県川崎市高津区久末**********,S14034,20160106,0-00000000-0

---
> S-012: 店舗データ（store）から、住所 (address) に"横浜市"が含まれるものだけ全項目表示せよ。

In [61]:
%%sql
select *
from store
where address like '%横浜市%';

 * postgresql://padwan:***@localhost:5432/dsdojo_db
11 rows affected.

,store_cd,store_name,prefecture_cd,prefecture,address,address_kana,tel_no,longitude,latitude,floor_area
0,S14010,菊名店,14,神奈川県,神奈川県横浜市港北区菊名一丁目,カナガワケンヨコハマシコウホククキクナイッチョウメ,045-123-4032,139.6326,35.50049,1732.0
1,S14033,阿久和店,14,神奈川県,神奈川県横浜市瀬谷区阿久和西一丁目,カナガワケンヨコハマシセヤクアクワニシイッチョウメ,045-123-4043,139.4961,35.45918,1495.0
2,S14040,長津田店,14,神奈川県,神奈川県横浜市緑区長津田みなみ台五丁目,カナガワケンヨコハマシミドリクナガツタミナミダイゴチョウメ,045-123-4046,139.4994,35.52398,1548.0
3,S14050,阿久和西店,14,神奈川県,神奈川県横浜市瀬谷区阿久和西一丁目,カナガワケンヨコハマシセヤクアクワニシイッチョウメ,045-123-4053,139.4961,35.45918,1830.0
4,S14028,二ツ橋店,14,神奈川県,神奈川県横浜市瀬谷区二ツ橋町,カナガワケンヨコハマシセヤクフタツバシチョウ,045-123-4042,139.4963,35.46304,1574.0
5,S14012,本牧和田店,14,神奈川県,神奈川県横浜市中区本牧和田,カナガワケンヨコハマシナカクホンモクワダ,045-123-4034,139.6582,35.42156,1341.0
6,S14046,北山田店,14,神奈川県,神奈川県横浜市都筑区北山田一丁目,カナガワケンヨコハマシツヅキクキタヤマタイッチョウメ,045-123-4049,139.5916,35.56189,831.0
7,S14011,日吉本町店,14,神奈川県,神奈川県横浜市港北区日吉本町四丁目,カナガワケンヨコハマシコウホククヒヨシホンチョウヨンチョウメ,045-123-4033,139.6316,35.54655,890.0
8,S14048,中川中央店,14,神奈川県,神奈川県横浜市都筑区中川中央二丁目,カナガワケンヨコハマシツヅキクナカガワチュウオウニチョウメ,045-123-4051,139.5758,35.54912,1657.0
9,S14042,新山下店,14,神奈川県,神奈川県横浜市中区新山下二丁目,カナガワケンヨコハマシナカクシンヤマシタニチョウメ,045-123-4047,139.6593,35.43894,1044.0
10,S14006,葛が谷店,14,神奈川県,神奈川県横浜市都筑区葛が谷,カナガワケンヨコハマシツヅキククズガヤ,045-123-4031,139.5633,35.53573,1886.0

---
> S-013: 顧客データ（customer）から、ステータスコード（status_cd）の先頭がアルファベットのA〜Fで始まるデータを全項目抽出し、10件表示せよ。

In [62]:
%%sql
select *
from customer
where status_cd ~ '^[A:F]'
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,customer_id,customer_name,gender_cd,gender,birth_day,age,postal_cd,address,application_store_cd,application_date,status_cd
0,CS035415000029,寺沢 真希,9,不明,1977-09-27,41,158-0096,東京都世田谷区玉川台**********,S13035,20141220,F-20101029-F
1,CS031415000106,宇野 由美子,1,女性,1970-02-26,49,151-0053,東京都渋谷区代々木**********,S13031,20150201,F-20100511-E
2,CS033605000005,猪股 雄太,0,男性,1955-12-05,63,246-0031,神奈川県横浜市瀬谷区瀬谷**********,S14033,20150425,F-20100917-E
3,CS033415000229,板垣 菜々美,1,女性,1977-11-07,41,246-0021,神奈川県横浜市瀬谷区二ツ橋町**********,S14033,20150712,F-20100326-E
4,CS008415000145,黒谷 麻緒,1,女性,1977-06-27,41,157-0067,東京都世田谷区喜多見**********,S13008,20150829,F-20100622-F
5,CS022513000105,島村 貴美子,1,女性,1962-03-12,57,249-0002,神奈川県逗子市山の根**********,S14022,20150320,A-20091115-7
6,CS001515000096,水野 陽子,9,不明,1960-11-29,58,144-0053,東京都大田区蒲田本町**********,S13001,20150614,A-20100724-7
7,CS028415000057,山内 瞬,1,女性,1975-08-26,43,246-0035,神奈川県横浜市瀬谷区下瀬谷**********,S14028,20150518,F-20100908-F
8,CS022414000100,戸田 そら,1,女性,1973-10-19,45,249-0006,神奈川県逗子市逗子**********,S14022,20150926,A-20090814-C
9,CS024305000004,佐久間 花緑,0,男性,1982-03-16,37,214-0039,神奈川県川崎市多摩区栗谷**********,S14024,20150625,A-20100924-A

---
> S-014: 顧客データ（customer）から、ステータスコード（status_cd）の末尾が数字の1〜9で終わるデータを全項目抽出し、10件表示せよ。

In [63]:
%%sql
select *
from customer
where status_cd ~ '[1-9]$'
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,customer_id,customer_name,gender_cd,gender,birth_day,age,postal_cd,address,application_store_cd,application_date,status_cd
0,CS001215000145,田崎 美紀,1,女性,1995-03-29,24,144-0055,東京都大田区仲六郷**********,S13001,20170605,6-20090929-2
1,CS033513000180,安斎 遥,1,女性,1962-07-11,56,241-0823,神奈川県横浜市旭区善部町**********,S14033,20150728,6-20080506-5
2,CS011215000048,芦田 沙耶,1,女性,1992-02-01,27,223-0062,神奈川県横浜市港北区日吉本町**********,S14011,20150228,C-20100421-9
3,CS040412000191,川井 郁恵,1,女性,1977-01-05,42,226-0021,神奈川県横浜市緑区北八朔町**********,S14040,20151101,1-20091025-4
4,CS009315000023,皆川 文世,1,女性,1980-04-15,38,154-0012,東京都世田谷区駒沢**********,S13009,20150319,5-20080322-1
5,CS015315000033,福士 璃奈子,1,女性,1983-03-17,36,135-0043,東京都江東区塩浜**********,S13015,20141024,4-20080219-3
6,CS023513000066,神戸 そら,1,女性,1961-12-17,57,210-0005,神奈川県川崎市川崎区東田町**********,S14023,20150915,5-20100524-9
7,CS035513000134,市川 美帆,1,女性,1960-03-27,59,156-0053,東京都世田谷区桜**********,S13035,20150227,8-20100711-9
8,CS001515000263,高松 夏空,1,女性,1962-11-09,56,144-0051,東京都大田区西蒲田**********,S13001,20160812,1-20100804-1
9,CS040314000027,鶴田 きみまろ,9,不明,1986-03-26,33,226-0027,神奈川県横浜市緑区長津田**********,S14040,20150122,2-20080426-4

---
> S-015: 顧客データ（customer）から、ステータスコード（status_cd）の先頭がアルファベットのA〜Fで始まり、末尾が数字の1〜9で終わるデータを全項目抽出し、10件表示せよ。

In [64]:
%%sql
select *
from customer
where status_cd ~ '^[A:F].*[1-9]$'
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,customer_id,customer_name,gender_cd,gender,birth_day,age,postal_cd,address,application_store_cd,application_date,status_cd
0,CS022513000105,島村 貴美子,1,女性,1962-03-12,57,249-0002,神奈川県逗子市山の根**********,S14022,20150320,A-20091115-7
1,CS001515000096,水野 陽子,9,不明,1960-11-29,58,144-0053,東京都大田区蒲田本町**********,S13001,20150614,A-20100724-7
2,CS001215000097,竹中 あさみ,1,女性,1990-07-25,28,146-0095,東京都大田区多摩川**********,S13001,20170315,A-20100211-2
3,CS001615000372,稲垣 寿々花,1,女性,1956-10-29,62,144-0035,東京都大田区南蒲田**********,S13001,20170403,A-20100104-1
4,CS032512000121,松井 知世,1,女性,1962-09-04,56,210-0011,神奈川県川崎市川崎区富士見**********,S13032,20150727,A-20100103-5
5,CS001514000191,高倉 礼子,1,女性,1965-11-04,53,144-0046,東京都大田区東六郷**********,S13001,20160628,A-20100731-1
6,CS008315000012,須藤 沙知絵,9,不明,1987-08-24,31,157-0074,東京都世田谷区大蔵**********,S13008,20151226,A-20090320-8
7,CS004413000091,小田 めぐみ,9,不明,1973-02-15,46,176-0024,東京都練馬区中村**********,S13004,20150921,A-20080512-1
8,CS039413000264,尾崎 菜摘,1,女性,1970-05-18,48,167-0051,東京都杉並区荻窪**********,S13039,20150621,A-20100221-4
9,CS014413000002,荻原 さゆり,1,女性,1970-03-20,49,264-0032,千葉県千葉市若葉区みつわ台**********,S12014,20150517,A-20080414-4

---
> S-016: 店舗データ（store）から、電話番号（tel_no）が3桁-3桁-4桁のデータを全項目表示せよ。

In [71]:
%%sql

SELECT * FROM store WHERE tel_no ~ '^[0-9]{3}-[0-9]{3}-[0-9]{4}$';

 * postgresql://padwan:***@localhost:5432/dsdojo_db
0 rows affected.

Empty DataFrame
Columns: []
Index: []

---
> S-017: 顧客データ（customer）を生年月日（birth_day）で高齢順にソートし、先頭から全項目を10件表示せよ。

In [72]:
%%sql
select *
from customer
order by birth_day asc
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,customer_id,customer_name,gender_cd,gender,birth_day,age,postal_cd,address,application_store_cd,application_date,status_cd
0,CS003813000014,村山 菜々美,1,女性,1928-11-26,90,182-0007,東京都調布市菊野台**********,S13003,20160214,0-00000000-0
1,CS026813000004,吉村 朝陽,1,女性,1928-12-14,90,251-0043,神奈川県藤沢市辻堂元町**********,S14026,20150723,0-00000000-0
2,CS018811000003,熊沢 美里,1,女性,1929-01-07,90,204-0004,東京都清瀬市野塩**********,S13018,20150403,0-00000000-0
3,CS027803000004,内村 拓郎,0,男性,1929-01-12,90,251-0031,神奈川県藤沢市鵠沼藤が谷**********,S14027,20151227,0-00000000-0
4,CS013801000003,天野 拓郎,0,男性,1929-01-15,90,274-0824,千葉県船橋市前原東**********,S12013,20160120,0-00000000-0
5,CS001814000022,鶴田 里穂,1,女性,1929-01-28,90,144-0045,東京都大田区南六郷**********,S13001,20161012,A-20090415-7
6,CS016815000002,山元 美紀,1,女性,1929-02-22,90,184-0005,東京都小金井市桜町**********,S13016,20150629,C-20090923-C
7,CS009815000003,中田 里穂,1,女性,1929-04-08,89,154-0014,東京都世田谷区新町**********,S13009,20150421,D-20091021-E
8,CS012813000013,宇野 南朋,1,女性,1929-04-09,89,231-0806,神奈川県横浜市中区本牧町**********,S14012,20150712,0-00000000-0
9,CS005813000015,金谷 恵梨香,1,女性,1929-04-09,89,165-0032,東京都中野区鷺宮**********,S13005,20150506,0-00000000-0

---
> S-018: 顧客データ（customer）を生年月日（birth_day）で若い順にソートし、先頭から全項目を10件表示せよ。

In [73]:
%%sql
select *
from customer
order by birth_day desc
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,customer_id,customer_name,gender_cd,gender,birth_day,age,postal_cd,address,application_store_cd,application_date,status_cd
0,CS035114000004,大村 美里,1,女性,2007-11-25,11,156-0053,東京都世田谷区桜**********,S13035,20150619,6-20091205-6
1,CS022103000002,福山 はじめ,9,不明,2007-10-02,11,249-0006,神奈川県逗子市逗子**********,S14022,20160909,0-00000000-0
2,CS002113000009,柴田 真悠子,1,女性,2007-09-17,11,184-0014,東京都小金井市貫井南町**********,S13002,20160304,0-00000000-0
3,CS004115000014,松井 京子,1,女性,2007-08-09,11,165-0031,東京都中野区上鷺宮**********,S13004,20161120,1-20081231-1
4,CS002114000010,山内 遥,1,女性,2007-06-03,11,184-0015,東京都小金井市貫井北町**********,S13002,20160920,6-20100510-1
5,CS025115000002,小柳 夏希,1,女性,2007-04-18,11,245-0018,神奈川県横浜市泉区上飯田町**********,S14025,20160116,D-20100913-D
6,CS002113000025,広末 まなみ,1,女性,2007-03-30,12,184-0015,東京都小金井市貫井北町**********,S13002,20171030,0-00000000-0
7,CS033112000003,長野 美紀,1,女性,2007-03-22,12,245-0051,神奈川県横浜市戸塚区名瀬町**********,S14033,20150606,0-00000000-0
8,CS007115000006,福岡 瞬,1,女性,2007-03-10,12,285-0845,千葉県佐倉市西志津**********,S12007,20151118,F-20101016-F
9,CS014113000008,矢口 莉緒,1,女性,2007-03-05,12,260-0041,千葉県千葉市中央区東千葉**********,S12014,20150622,3-20091108-6

---
> S-019: レシート明細データ（receipt）に対し、1件あたりの売上金額（amount）が高い順にランクを付与し、先頭から10件表示せよ。項目は顧客ID（customer_id）、売上金額（amount）、付与したランクを表示させること。なお、売上金額（amount）が等しい場合は同一順位を付与するものとする。

In [74]:
%%sql
select customer_id,amount,rank() over(order by amount desc) as ranking
from receipt
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

      customer_id  amount  ranking
0  CS011415000006   10925        1
1  ZZ000000000000    6800        2
2  CS028605000002    5780        3
3  CS015515000034    5480        4
4  ZZ000000000000    5480        4
5  ZZ000000000000    5480        4
6  ZZ000000000000    5440        7
7  CS021515000089    5440        7
8  CS009415000038    5280        9
9  ZZ000000000000    5280        9

---
> S-020: レシート明細データ（receipt）に対し、1件あたりの売上金額（amount）が高い順にランクを付与し、先頭から10件表示せよ。項目は顧客ID（customer_id）、売上金額（amount）、付与したランクを表示させること。なお、売上金額（amount）が等しい場合でも別順位を付与すること。

In [75]:
%%sql
select customer_id,amount,row_number() over(order by amount desc) as ranking
from receipt
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

      customer_id  amount  ranking
0  CS011415000006   10925        1
1  ZZ000000000000    6800        2
2  CS028605000002    5780        3
3  ZZ000000000000    5480        4
4  ZZ000000000000    5480        5
5  CS015515000034    5480        6
6  ZZ000000000000    5440        7
7  CS021515000089    5440        8
8  ZZ000000000000    5280        9
9  ZZ000000000000    5280       10

---
> S-021: レシート明細データ（receipt）に対し、件数をカウントせよ。

In [76]:
%%sql
select COUNT(1)
from receipt;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
1 rows affected.

    count
0  104681

---
> S-022: レシート明細データ（receipt）の顧客ID（customer_id）に対し、ユニーク件数をカウントせよ。

In [77]:
%%sql
select count(distinct customer_id)
from receipt;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
1 rows affected.

   count
0   8307

---
> S-023: レシート明細データ（receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）と売上数量（quantity）を合計せよ。

In [79]:
%%sql
select store_cd,SUM(amount) as amount,SUM(quantity) as quantity
from receipt
group by store_cd;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
52 rows affected.

   store_cd  amount  quantity
0    S12007  638761      2099
1    S13017  748221      2376
2    S13043  587895      1881
3    S13052  100314       250
4    S13016  793773      2432
5    S14027  714550      2303
6    S13009  808870      2486
7    S14022  651328      2047
8    S13019  827833      2541
9    S13039  611888      1981
10   S14046  412646      1354
11   S13003  764294      2197
12   S14028  786145      2458
13   S14045  458484      1398
14   S13002  727821      2340
15   S14042  534689      1935
16   S13004  779373      2390
17   S13038  708884      2337
18   S12014  725167      2358
19   S14021  699511      2231
20   S14006  712839      2284
21   S13001  811936      2347
22   S14023  727630      2258
23   S14025  755581      2394
24   S13035  715869      2219
25   S14048  234276       769
26   S14012  720600      2412
27   S14024  736323      2417
28   S13041  728266      2233
29   S14026  824537      2503
30   S14010  790361      2290
31   S13015  780873      2248
32   S13008  809288      2491
33   S14049  230808       788
34   S14050  167090       580
35   S13031  705968      2336
36   S12013  787513      2425
37   S13044  520764      1729
38   S14033  725318      2282
39   S12029  794741      2555
40   S13037  693087      2344
41   S12030  684402      2403
42   S13032  790501      2491
43   S14034  653681      2024
44   S14040  701858      2233
45   S13005  629876      2004
46   S14047  338329      1041
47   S14011  805724      2434
48   S13018  790535      2562
49   S13020  796383      2383
50   S13051  107452       354
51   S14036  203694       635

---
> S-024: レシート明細データ（receipt）に対し、顧客ID（customer_id）ごとに最も新しい売上年月日（sales_ymd）を求め、10件表示せよ。

In [81]:
%%sql
select customer_id,max(sales_ymd)
from receipt
group by customer_id
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

      customer_id       max
0  CS001311000059  20180211
1  CS004614000122  20181228
2  CS003512000043  20180106
3  CS011615000061  20190503
4  CS029212000033  20180621
5  CS007515000119  20190511
6  CS034515000123  20190708
7  CS004315000058  20170517
8  CS026414000014  20190720
9  CS001615000099  20170729

---
> S-025: レシート明細データ（receipt）に対し、顧客ID（customer_id）ごとに最も古い売上年月日（sales_ymd）を求め、10件表示せよ。

In [83]:
%%sql
select customer_id,min(sales_ymd)
from receipt
group by customer_id
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

      customer_id       min
0  CS001311000059  20180211
1  CS004614000122  20181228
2  CS003512000043  20180106
3  CS011615000061  20190503
4  CS029212000033  20170318
5  CS007515000119  20170201
6  CS034515000123  20170527
7  CS004315000058  20170517
8  CS026414000014  20170718
9  CS001615000099  20170729

---
> S-026: レシート明細データ（receipt）に対し、顧客ID（customer_id）ごとに最も新しい売上年月日（sales_ymd）と古い売上年月日を求め、両者が異なるデータを10件表示せよ。

In [84]:
%%sql
select customer_id,max(sales_ymd),min(sales_ymd)
from receipt
group by customer_id
having max(sales_ymd) != min(sales_ymd)
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

      customer_id       max       min
0  CS029212000033  20180621  20170318
1  CS007515000119  20190511  20170201
2  CS034515000123  20190708  20170527
3  CS026414000014  20190720  20170718
4  CS010515000082  20181204  20180518
5  CS019315000045  20170920  20170423
6  CS008513000099  20190308  20170722
7  CS007615000070  20191025  20170929
8  CS025415000155  20191026  20170314
9  CS016414000063  20190617  20170109

---
> S-027: レシート明細データ（receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の平均を計算し、降順でTOP5を表示せよ。

In [86]:
%%sql
select store_cd,AVG(amount)
from receipt
group by store_cd
order by avg(amount) desc
limit 5;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
5 rows affected.

  store_cd                   avg
0   S13052  402.8674698795180723
1   S13015  351.1119604316546763
2   S13003  350.9155188246097337
3   S14010  348.7912621359223301
4   S13001  348.4703862660944206

---
> S-028: レシート明細データ（receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の中央値を計算し、降順でTOP5を表示せよ。

In [87]:
%%sql
select store_cd,PERCENTILE_CONT(0.5) within group (order by amount) as med
from receipt
group by store_cd
order by med desc
limit 5;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
5 rows affected.

  store_cd    med
0   S13052  190.0
1   S14010  188.0
2   S14050  185.0
3   S13003  180.0
4   S13018  180.0

---
> S-029: レシート明細データ（receipt）に対し、店舗コード（store_cd）ごとに商品コード（product_cd）の最頻値を求め、10件表示させよ。

In [91]:
%%sql
select store_cd,mode() within group (order by product_cd)
from receipt
group by store_cd
order by store_cd
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

  store_cd        mode
0   S12007  P060303001
1   S12013  P060303001
2   S12014  P060303001
3   S12029  P060303001
4   S12030  P060303001
5   S13001  P060303001
6   S13002  P060303001
7   S13003  P071401001
8   S13004  P060303001
9   S13005  P040503001

---
> S-030: レシート明細データ（receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の分散を計算し、降順で5件表示せよ。

In [93]:
%%sql
select store_cd,VAR_SAMP(amount) as var
from receipt
group by store_cd
order by var desc
limit 5;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
5 rows affected.

  store_cd                  var
0   S13052  441863.252526233968
1   S14011  306442.242431568709
2   S14034  297068.392740060738
3   S13001  295558.842617712478
4   S13015  295427.197085853584

---
> S-031: レシート明細データ（receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の標準偏差を計算し、降順で5件表示せよ。

In [94]:
%%sql
select store_cd,STDDEV_SAMP(amount) as std
from receipt
group by store_cd
order by std desc
limit 5;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
5 rows affected.

  store_cd               std
0   S13052  664.727953772244
1   S14011  553.572255836190
2   S14034  545.039808399406
3   S13001  543.653237475610
4   S13015  543.532149082144

---
> S-032: レシート明細データ（receipt）の売上金額（amount）について、25％刻みでパーセンタイル値を求めよ。

In [96]:
%%sql
select
  PERCENTILE_CONT(0.25) within group (order by amount) as "25%",
  PERCENTILE_CONT(0.5) within group (order by amount) as "50%",
  PERCENTILE_CONT(0.75) within group (order by amount) as "75%",
  PERCENTILE_CONT(1) within group (order by amount) as "100%"
from receipt;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
1 rows affected.

     25%    50%    75%     100%
0  102.0  170.0  288.0  10925.0

---
> S-033: レシート明細データ（receipt）に対し、店舗コード（store_cd）ごとに売上金額（amount）の平均を計算し、330以上のものを抽出せよ。

In [98]:
%%sql
select store_cd,avg(amount) as avg
from receipt
group by store_cd
having AVG(amount) >= 330;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
13 rows affected.

   store_cd                   avg
0    S13052  402.8674698795180723
1    S13019  330.2086158755484643
2    S13003  350.9155188246097337
3    S14045  330.0820734341252700
4    S13004  330.9439490445859873
5    S13001  348.4703862660944206
6    S14026  332.3405884723901653
7    S14010  348.7912621359223301
8    S13015  351.1119604316546763
9    S12013  330.1941299790356394
10   S14047  330.0770731707317073
11   S14011  335.7183333333333333
12   S13020  337.8799321170980059

---
> S-034: レシート明細データ（receipt）に対し、顧客ID（customer_id）ごとに売上金額（amount）を合計して全顧客の平均を求めよ。ただし、顧客IDが"Z"から始まるものは非会員を表すため、除外して計算すること。

In [106]:
%%sql
with customer_amount as (
  select customer_id,sum(amount) as sum_amount
  from receipt
  where customer_id not like 'Z%'
  group by customer_id
)

select customer_id,sum_amount
from customer_amount
limit 5;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
5 rows affected.

      customer_id  sum_amount
0  CS001311000059        2302
1  CS004614000122         248
2  CS003512000043         298
3  CS011615000061         246
4  CS029212000033        3604

---
> S-035: レシート明細データ（receipt）に対し、顧客ID（customer_id）ごとに売上金額（amount）を合計して全顧客の平均を求め、平均以上に買い物をしている顧客を抽出し、10件表示せよ。ただし、顧客IDが"Z"から始まるものは非会員を表すため、除外して計算すること。

In [107]:
%%sql
with customer_amount as (
  select customer_id,sum(amount) as sum_amount
  from receipt
  where customer_id not like 'Z%'
  group by customer_id
)

select customer_id,sum_amount
from customer_amount
where sum_amount >= (select avg(sum_amount) from customer_amount)
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

      customer_id  sum_amount
0  CS029212000033        3604
1  CS007515000119        7157
2  CS034515000123        3699
3  CS026414000014        6671
4  CS007615000070        2975
5  CS016414000063        6207
6  CS012514000018        2562
7  CS029515000142        3420
8  CS015215000021        3090
9  CS039814000011        8031

---
> S-036: レシート明細データ（receipt）と店舗データ（store）を内部結合し、レシート明細データの全項目と店舗データの店舗名（store_name）を10件表示せよ。

In [108]:
%%sql
select receipt.*,store.store_name
from receipt
join store
on receipt.store_cd = store.store_cd
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,sales_ymd,sales_epoch,store_cd,receipt_no,receipt_sub_no,customer_id,product_cd,quantity,amount,store_name
0,20181103,1541203200,S14006,112,1,CS006214000001,P070305012,1,158,葛が谷店
1,20181118,1542499200,S13008,1132,2,CS008415000097,P070701017,1,81,成城店
2,20170712,1499817600,S14028,1102,1,CS028414000014,P060101005,1,170,二ツ橋店
3,20190205,1549324800,S14042,1132,1,ZZ000000000000,P050301001,1,25,新山下店
4,20180821,1534809600,S14025,1102,2,CS025415000050,P060102007,1,90,大和店
5,20190605,1559692800,S13003,1112,1,CS003515000195,P050102002,1,138,狛江店
6,20181205,1543968000,S14024,1102,2,CS024514000042,P080101005,1,30,三田店
7,20190922,1569110400,S14040,1102,1,CS040415000178,P070501004,1,128,長津田店
8,20170504,1493856000,S13020,1112,2,ZZ000000000000,P071302010,1,770,十条仲原店
9,20191010,1570665600,S14027,1102,1,CS027514000015,P071101003,1,680,南藤沢店

---
> S-037: 商品データ（product）とカテゴリデータ（category）を内部結合し、商品データの全項目とカテゴリデータのカテゴリ小区分名（category_small_name）を10件表示せよ。

In [110]:
%%sql
select product.*,category.category_small_cd
from product
join category
on product.category_small_cd = category.category_small_cd
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

,product_cd,category_major_cd,category_medium_cd,category_small_cd,unit_price,unit_cost,category_small_cd
0,P040101001,04,0401,040101,198,149,040101
1,P040101002,04,0401,040101,218,164,040101
2,P040101003,04,0401,040101,230,173,040101
3,P040101004,04,0401,040101,248,186,040101
4,P040101005,04,0401,040101,268,201,040101
5,P040101006,04,0401,040101,298,224,040101
6,P040101007,04,0401,040101,338,254,040101
7,P040101008,04,0401,040101,420,315,040101
8,P040101009,04,0401,040101,498,374,040101
9,P040101010,04,0401,040101,580,435,040101

---
> S-038: 顧客データ（customer）とレシート明細データ（receipt）から、顧客ごとの売上金額合計を求め、10件表示せよ。ただし、売上実績がない顧客については売上金額を0として表示させること。また、顧客は性別コード（gender_cd）が女性（1）であるものを対象とし、非会員（顧客IDが"Z"から始まるもの）は除外すること。

In [112]:
%%sql
with customer_amount as (
  select customer_id,sum(amount) as sum_amount
  from receipt
  group by customer_id
)
select c.customer_id,COALESCE(a.sum_amount,0)
from customer c
left join customer_amount a
on c.customer_id = a.customer_id
where c.gender_cd = '1' and c.customer_id not like 'Z%'
limit 10;

 * postgresql://padwan:***@localhost:5432/dsdojo_db
10 rows affected.

      customer_id  coalesce
0  CS021313000114         0
1  CS031415000172      5088
2  CS028811000001         0
3  CS001215000145       875
4  CS015414000103      3122
5  CS033513000180       868
6  CS035614000014         0
7  CS011215000048      3444
8  CS009413000079         0
9  CS040412000191       210

---
> S-039: レシート明細データ（receipt）から、売上日数の多い顧客の上位20件を抽出したデータと、売上金額合計の多い顧客の上位20件を抽出したデータをそれぞれ作成し、さらにその2つを完全外部結合せよ。ただし、非会員（顧客IDが"Z"から始まるもの）は除外すること。

In [ ]:
%%sql

---
> S-040: 全ての店舗と全ての商品を組み合わせたデータを作成したい。店舗データ（store）と商品データ（product）を直積し、件数を計算せよ。

In [ ]:
%%sql

---
> S-041: レシート明細データ（receipt）の売上金額（amount）を日付（sales_ymd）ごとに集計し、前回売上があった日からの売上金額増減を計算せよ。そして結果を10件表示せよ。

In [ ]:
%%sql

---
> S-042: レシート明細データ（receipt）の売上金額（amount）を日付（sales_ymd）ごとに集計し、各日付のデータに対し、前回、前々回、3回前に売上があった日のデータを結合せよ。そして結果を10件表示せよ。

In [ ]:
%%sql

---
> S-043: レシート明細データ（receipt）と顧客データ（customer）を結合し、性別コード（gender_cd）と年代（ageから計算）ごとに売上金額（amount）を合計した売上サマリデータを作成せよ。性別コードは0が男性、1が女性、9が不明を表すものとする。
>
> ただし、項目構成は年代、女性の売上金額、男性の売上金額、性別不明の売上金額の4項目とすること（縦に年代、横に性別のクロス集計）。また、年代は10歳ごとの階級とすること。

In [ ]:
%%sql

---
> S-044: 043で作成した売上サマリデータ（sales_summary）は性別の売上を横持ちさせたものであった。このデータから性別を縦持ちさせ、年代、性別コード、売上金額の3項目に変換せよ。ただし、性別コードは男性を"00"、女性を"01"、不明を"99"とする。    
>> **※ Colaboratoryで演習を再開したときは、解答前にS-043の解答を実行して下さい**

In [ ]:
%%sql

---
> S-045: 顧客データ（customer）の生年月日（birth_day）は日付型でデータを保有している。これをYYYYMMDD形式の文字列に変換し、顧客ID（customer_id）とともに10件表示せよ。

In [ ]:
%%sql

---
> S-046: 顧客データ（customer）の申し込み日（application_date）はYYYYMMDD形式の文字列型でデータを保有している。これを日付型に変換し、顧客ID（customer_id）とともに10件表示せよ。

In [ ]:
%%sql

---
> S-047: レシート明細データ（receipt）の売上日（sales_ymd）はYYYYMMDD形式の数値型でデータを保有している。これを日付型に変換し、レシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。

In [ ]:
%%sql

---
> S-048: レシート明細データ（receipt）の売上エポック秒（sales_epoch）は数値型のUNIX秒でデータを保有している。これを日付型に変換し、レシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。

In [ ]:
%%sql

---
> S-049: レシート明細データ（receipt）の売上エポック秒（sales_epoch）を日付型に変換し、「年」だけ取り出してレシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。

In [ ]:
%%sql

---
> S-050: レシート明細データ（receipt）の売上エポック秒（sales_epoch）を日付型に変換し、「月」だけ取り出してレシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。なお、「月」は0埋め2桁で取り出すこと。

In [ ]:
%%sql

---
> S-051: レシート明細データ（receipt）の売上エポック秒を日付型に変換し、「日」だけ取り出してレシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。なお、「日」は0埋め2桁で取り出すこと。

In [ ]:
%%sql

---
> S-052: レシート明細データ（receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計の上、売上金額合計に対して2,000円以下を0、2,000円より大きい金額を1に二値化し、顧客ID、売上金額合計とともに10件表示せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

In [ ]:
%%sql

---
> S-053: 顧客データ（customer）の郵便番号（postal_cd）に対し、東京（先頭3桁が100〜209のもの）を1、それ以外のものを0に二値化せよ。さらにレシート明細データ（receipt）と結合し、全期間において売上実績のある顧客数を、作成した二値ごとにカウントせよ。

In [ ]:
%%sql

---
> S-054: 顧客データ（customer）の住所（address）は、埼玉県、千葉県、東京都、神奈川県のいずれかとなっている。都道府県毎にコード値を作成し、顧客ID、住所とともに10件表示せよ。値は埼玉県を11、千葉県を12、東京都を13、神奈川県を14とすること。

In [ ]:
%%sql

---
> S-055: レシート明細（receipt）データの売上金額（amount）を顧客ID（customer_id）ごとに合計し、その合計金額の四分位点を求めよ。その上で、顧客ごとの売上金額合計に対して以下の基準でカテゴリ値を作成し、顧客ID、売上金額合計とともに10件表示せよ。カテゴリ値は順に1〜4とする。
>
> - 最小値以上第1四分位未満 ・・・ 1を付与
> - 第1四分位以上第2四分位未満 ・・・ 2を付与
> - 第2四分位以上第3四分位未満 ・・・ 3を付与
> - 第3四分位以上 ・・・ 4を付与

In [ ]:
%%sql

---
> S-056: 顧客データ（customer）の年齢（age）をもとに10歳刻みで年代を算出し、顧客ID（customer_id）、生年月日（birth_day）とともに10件表示せよ。ただし、60歳以上は全て60歳代とすること。年代を表すカテゴリ名は任意とする。

In [ ]:
%%sql

---
> S-057: 056の抽出結果と性別コード（gender_cd）により、新たに性別×年代の組み合わせを表すカテゴリデータを作成し、10件表示せよ。組み合わせを表すカテゴリの値は任意とする。

In [ ]:
%%sql

---
> S-058: 顧客データ（customer）の性別コード（gender_cd）をダミー変数化し、顧客ID（customer_id）とともに10件表示せよ。

In [ ]:
%%sql

---
> S-059: レシート明細データ（receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、売上金額合計を平均0、標準偏差1に標準化して顧客ID、売上金額合計とともに10件表示せよ。標準化に使用する標準偏差は、分散の平方根、もしくは不偏分散の平方根のどちらでも良いものとする。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

In [ ]:
%%sql

---
> S-060: レシート明細データ（receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、売上金額合計を最小値0、最大値1に正規化して顧客ID、売上金額合計とともに10件表示せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

In [ ]:
%%sql

---
> S-061: レシート明細データ（receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、売上金額合計を常用対数化（底10）して顧客ID、売上金額合計とともに10件表示せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

In [ ]:
%%sql

---
> S-062: レシート明細データ（receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、売上金額合計を自然対数化（底e）して顧客ID、売上金額合計とともに10件表示せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。

In [ ]:
%%sql

---
> S-063: 商品データ（product）の単価（unit_price）と原価（unit_cost）から各商品の利益額を算出し、結果を10件表示せよ。

In [ ]:
%%sql

---
> S-064: 商品データ（product）の単価（unit_price）と原価（unit_cost）から、各商品の利益率の全体平均を算出せよ。ただし、単価と原価には欠損が生じていることに注意せよ。

In [ ]:
%%sql

---
> S-065: 商品データ（product）の各商品について、利益率が30%となる新たな単価を求めよ。ただし、1円未満は切り捨てること。そして結果を10件表示させ、利益率がおよそ30％付近であることを確認せよ。ただし、単価（unit_price）と原価（unit_cost）には欠損が生じていることに注意せよ。

In [ ]:
%%sql

---
> S-066: 商品データ（product）の各商品について、利益率が30%となる新たな単価を求めよ。今回は、1円未満を丸めること（四捨五入または偶数への丸めで良い）。そして結果を10件表示させ、利益率がおよそ30％付近であることを確認せよ。ただし、単価（unit_price）と原価（unit_cost）には欠損が生じていることに注意せよ。

In [ ]:
%%sql

---
> S-067: 商品データ（product）の各商品について、利益率が30%となる新たな単価を求めよ。今回は、1円未満を切り上げること。そして結果を10件表示させ、利益率がおよそ30％付近であることを確認せよ。ただし、単価（unit_price）と原価（unit_cost）には欠損が生じていることに注意せよ。

In [ ]:
%%sql

---
> S-068: 商品データ（product）の各商品について、消費税率10％の税込み金額を求めよ。1円未満の端数は切り捨てとし、結果を10件表示せよ。ただし、単価（unit_price）には欠損が生じていることに注意せよ。

In [ ]:
%%sql

---
> S-069: レシート明細データ（receipt）と商品データ（product）を結合し、顧客毎に全商品の売上金額合計と、カテゴリ大区分コード（category_major_cd）が"07"（瓶詰缶詰）の売上金額合計を計算の上、両者の比率を求めよ。抽出対象はカテゴリ大区分コード"07"（瓶詰缶詰）の売上実績がある顧客のみとし、結果を10件表示せよ。

In [ ]:
%%sql

---
> S-070: レシート明細データ（receipt）の売上日（sales_ymd）に対し、顧客データ（customer）の会員申込日（application_date）からの経過日数を計算し、顧客ID（customer_id）、売上日、会員申込日とともに10件表示せよ（sales_ymdは数値、application_dateは文字列でデータを保持している点に注意）。

In [ ]:
%%sql

---
> S-071: レシート明細データ（receipt）の売上日（sales_ymd）に対し、顧客データ（customer）の会員申込日（application_date）からの経過月数を計算し、顧客ID（customer_id）、売上日、会員申込日とともに10件表示せよ（sales_ymdは数値、application_dateは文字列でデータを保持している点に注意）。1ヶ月未満は切り捨てること。

In [ ]:
%%sql

---
> S-072: レシート明細データ（receipt）の売上日（sales_ymd）に対し、顧客データ（customer）の会員申込日（application_date）からの経過年数を計算し、顧客ID（customer_id）、売上日、会員申込日とともに10件表示せよ（sales_ymdは数値、application_dateは文字列でデータを保持している点に注意）。1年未満は切り捨てること。

In [ ]:
%%sql

---
> S-073: レシート明細データ（receipt）の売上日（sales_ymd）に対し、顧客データ（customer）の会員申込日（application_date）からのエポック秒による経過時間を計算し、顧客ID（customer_id）、売上日、会員申込日とともに10件表示せよ（なお、sales_ymdは数値、application_dateは文字列でデータを保持している点に注意）。なお、時間情報は保有していないため各日付は0時0分0秒を表すものとする。

In [ ]:
%%sql

---
> S-074: レシート明細データ（receipt）の売上日（sales_ymd）に対し、当該週の月曜日からの経過日数を計算し、売上日、直前の月曜日付とともに10件表示せよ（sales_ymdは数値でデータを保持している点に注意）。

In [ ]:
%%sql

---
> S-075: 顧客データ（customer）からランダムに1%のデータを抽出し、先頭から10件表示せよ。

In [ ]:
%%sql

---
> S-076: 顧客データ（customer）から性別コード（gender_cd）の割合に基づきランダムに10%のデータを層化抽出し、性別コードごとに件数を集計せよ。

In [ ]:
%%sql

---
> S-077: レシート明細データ（receipt）の売上金額を顧客単位に合計し、合計した売上金額の外れ値を抽出せよ。なお、外れ値は売上金額合計を対数化したうえで平均と標準偏差を計算し、その平均から3σを超えて離れたものとする（自然対数と常用対数のどちらでも可）。結果は10件表示せよ。

In [ ]:
%%sql

---
> S-078: レシート明細データ（receipt）の売上金額（amount）を顧客単位に合計し、合計した売上金額の外れ値を抽出せよ。ただし、顧客IDが"Z"から始まるのものは非会員を表すため、除外して計算すること。なお、ここでは外れ値を第1四分位と第3四分位の差であるIQRを用いて、「第1四分位数-1.5×IQR」を下回るもの、または「第3四分位数+1.5×IQR」を超えるものとする。結果は10件表示せよ。

In [ ]:
%%sql

---
> S-079: 商品データ（product）の各項目に対し、欠損数を確認せよ。

In [ ]:
%%sql

---
> S-080: 商品データ（product）のいずれかの項目に欠損が発生しているレコードを全て削除した新たな商品データを作成せよ。なお、削除前後の件数を表示させ、079で確認した件数だけ減少していることも確認すること。

In [ ]:
%%sql

---
> S-081: 単価（unit_price）と原価（unit_cost）の欠損値について、それぞれの平均値で補完した新たな商品データを作成せよ。なお、平均値については1円未満を丸めること（四捨五入または偶数への丸めで良い）。補完実施後、各項目について欠損が生じていないことも確認すること。

In [ ]:
%%sql

---
> S-082: 単価（unit_price）と原価（unit_cost）の欠損値について、それぞれの中央値で補完した新たな商品データを作成せよ。なお、中央値については1円未満を丸めること（四捨五入または偶数への丸めで良い）。補完実施後、各項目について欠損が生じていないことも確認すること。

In [ ]:
%%sql

---
> S-083: 単価（unit_price）と原価（unit_cost）の欠損値について、各商品のカテゴリ小区分コード（category_small_cd）ごとに算出した中央値で補完した新たな商品データを作成せよ。なお、中央値については1円未満を丸めること（四捨五入または偶数への丸めで良い）。補完実施後、各項目について欠損が生じていないことも確認すること。

In [ ]:
%%sql

---
> S-084: 顧客データ（customer）の全顧客に対して全期間の売上金額に占める2019年売上金額の割合を計算し、新たなデータを作成せよ。ただし、売上実績がない場合は0として扱うこと。そして計算した割合が0超のものを抽出し、結果を10件表示せよ。また、作成したデータに欠損が存在しないことを確認せよ。

In [ ]:
%%sql

---
> S-085: 顧客データ（customer）の全顧客に対し、郵便番号（postal_cd）を用いてジオコードデータ（geocode）を紐付け、新たな顧客データを作成せよ。ただし、1つの郵便番号（postal_cd）に複数の経度（longitude）、緯度（latitude）情報が紐づく場合は、経度（longitude）、緯度（latitude）の平均値を算出して使用すること。また、作成結果を確認するために結果を10件表示せよ。

In [ ]:
%%sql

---
> S-086: 085で作成した緯度経度つき顧客データに対し、会員申込店舗コード（application_store_cd）をキーに店舗データ（store）と結合せよ。そして申込み店舗の緯度（latitude）・経度情報（longitude)と顧客住所（address）の緯度・経度を用いて申込み店舗と顧客住所の距離（単位：km）を求め、顧客ID（customer_id）、顧客住所（address）、店舗住所（address）とともに表示せよ。計算式は以下の簡易式で良いものとするが、その他精度の高い方式を利用したライブラリを利用してもかまわない。結果は10件表示せよ。
>> **※ Colaboratoryで演習を再開したときは、解答前にS-085の解答を実行して下さい**
$$
緯度（ラジアン）：\phi \\
経度（ラジアン）：\lambda \\
距離L = 6371 * arccos(sin \phi_1 * sin \phi_2
+ cos \phi_1 * cos \phi_2 * cos(\lambda_1 − \lambda_2))
$$

In [ ]:
%%sql

---
> S-087: 顧客データ（customer）では、異なる店舗での申込みなどにより同一顧客が複数登録されている。名前（customer_name）と郵便番号（postal_cd）が同じ顧客は同一顧客とみなして1顧客1レコードとなるように名寄せした名寄顧客データを作成し、顧客データの件数、名寄顧客データの件数、重複数を算出せよ。ただし、同一顧客に対しては売上金額合計が最も高いものを残し、売上金額合計が同一もしくは売上実績がない顧客については顧客ID（customer_id）の番号が小さいものを残すこととする。

In [ ]:
%%sql

---
> S-088: 087で作成したデータを元に、顧客データに統合名寄IDを付与したデータを作成せよ。ただし、統合名寄IDは以下の仕様で付与するものとする。
>
> - 重複していない顧客：顧客ID（customer_id）を設定
> - 重複している顧客：前設問で抽出したレコードの顧客IDを設定
>
> 顧客IDのユニーク件数と、統合名寄IDのユニーク件数の差も確認すること。
>> **※ Colaboratoryで演習を再開したときは、解答前にS-087の解答を実行して下さい**

In [ ]:
%%sql

---
> S-089: 売上実績がある顧客を、予測モデル構築のため学習用データとテスト用データに分割したい。それぞれ8:2の割合でランダムにデータを分割せよ。

In [ ]:
%%sql

---
> S-090: レシート明細データ（receipt）は2017年1月1日〜2019年10月31日までのデータを有している。売上金額（amount）を月次で集計し、学習用に12ヶ月、テスト用に6ヶ月の時系列モデル構築用データを3セット作成せよ。

In [ ]:
%%sql

---
> S-091: 顧客データ（customer）の各顧客に対し、売上実績がある顧客数と売上実績がない顧客数が1:1となるようにアンダーサンプリングで抽出せよ。

In [ ]:
%%sql

---
> S-092: 顧客データ（customer）の性別について、第三正規形へと正規化せよ。

In [ ]:
%%sql

---
> S-093: 商品データ（product）では各カテゴリのコード値だけを保有し、カテゴリ名は保有していない。カテゴリデータ（category）と組み合わせて非正規化し、カテゴリ名を保有した新たな商品データを作成せよ。

In [ ]:
%%sql

---
> S-094: 093で作成したカテゴリ名付き商品データを以下の仕様でファイル出力せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|有り|UTF-8|
>
> ファイル出力先のパスは以下のようにすること（COPYコマンドの権限は付与済み）。
>
> |出力先|
> |:--:|
> |/tmp/data|
>
>> **※ Colaboratoryで演習を再開したときは、解答前にS-093の解答を実行して下さい**

In [ ]:
%%sql

---
> S-095: 093で作成したカテゴリ名付き商品データを以下の仕様でファイル出力せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|有り|CP932|
>
> PostgreSQLではShift_JISを指定することでCP932相当となる。ファイル出力先のパスは以下のようにすること（COPYコマンドの権限は付与済み）。
>
> |出力先|
> |:--:|
> |/tmp/data|
>
>> **※ Colaboratoryで演習を再開したときは、解答前にS-093の解答を実行して下さい**

In [ ]:
%%sql

---
> S-096: 093で作成したカテゴリ名付き商品データを以下の仕様でファイル出力せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|無し|UTF-8|
>
> ファイル出力先のパスは以下のようにすること（COPYコマンドの権限は付与済み）。
>
> |出力先|
> |:--:|
> |/tmp/data|
>
>> **※ Colaboratoryで演習を再開したときは、解答前にS-093の解答を実行して下さい**

In [ ]:
%%sql

---
> S-097: 094で作成した以下形式のファイルを読み込み、データを3件を表示させて正しく取り込まれていることを確認せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|有り|UTF-8|
>
>> **※ Colaboratoryで演習を再開したときは、解答前にS-093、S-094の解答を実行して下さい**

In [ ]:
%%sql

---
> S-098: 096で作成した以下形式のファイルを読み込み、データを3件を表示させて正しく取り込まれていることを確認せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |CSV（カンマ区切り）|ヘッダ無し|UTF-8|
>
>> **※ Colaboratoryで演習を再開したときは、解答前にS-093、S-096の解答を実行して下さい**

In [ ]:
%%sql

---
> S-099: 093で作成したカテゴリ名付き商品データを以下の仕様でファイル出力せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |TSV（タブ区切り）|有り|UTF-8|
>
> ファイル出力先のパスは以下のようにすること（COPYコマンドの権限は付与済み）。
>
> |出力先|
> |:--:|
> |/tmp/data|
>
>> **※ Colaboratoryで演習を再開したときは、解答前にS-093の解答を実行して下さい**

In [ ]:
%%sql

---
> S-100: 099で作成した以下形式のファイルを読み込み、データを3件を表示させて正しく取り込まれていることを確認せよ。
>
> |ファイル形式|ヘッダ有無|文字エンコーディング|
> |:--:|:--:|:--:|
> |TSV（タブ区切り）|有り|UTF-8|
>
>> **※ Colaboratoryで演習を再開したときは、解答前にS-093、S-099の解答を実行して下さい**

In [ ]:
%%sql

# これで１００本終わりです。おつかれさまでした！